on:
  workflow_dispatch:

jobs:
  get_caller_identity:
    name: Get Caller Identity (Hardened)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Hardened_GitHub_Actions_Role
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          aws-region: us-east-1
      - name: Fetch the caller identity
        run: |
          aws sts get-caller-identity
